<html>
<?php include 'includes/header.php';?>
<section>
 <h2 class="pageID"><?=$title?></h2>

<!-- MAKE SURE YOU GET YOUR (3) IMAGES SAVED INTO YOUR IMAGES FOLDER -->

 <p>
    <ul>
        <li> In 2019 the number of mobile phone users is expected to rise from 4.01 billion in 2013 to 5.07. [1]</li>
        <li> More than half of global web traffic is generated by mobile devices.[2]</li>
        <li> In 2015 Google announced that it would promote rankings of mobile friendly pages in searches.[2]</li>
        <li>  Responsive mobile websites and mobile apps serve different functions. Responsive sites are more accessible and easier to maintain, while mobile apps give users a unique UX experience and can be easier to use to accomplish a specific task.[1]</li>
        <li>Mobile apps are coded in platform specific languages as software.</li>
        <li> A responsive website can be made for both desktop and mobile devices while apps can only be used on mobile devices. Therefore, a responsive website can reach a wider audience. [2]</li>
        <li> From a UX perspective, responsive websites are more useful in building brand awareness and reaching a new audience, while mobile apps are better suited in providing a custom experience for returning users and people who already have a relationship with the sites information. [2]</li>
        <li> Updating mobile apps takes more time and requires a version review by app stores before updates can be made. Updating a responsive site is relatively easy and quick.</li>
        <li>The differences between consumer preference of app vs responsive is industry and function dependent. Consumers prefer responsive sites for information searches while preferring mobile apps for location and bill paying for example. [2]</li>
        <li> Mobile apps have faster loading and more efficient accessibility on mobile devices. [3]</li>
        
    </ul>
    </p>
 
</section>
<!-- END LEFT COL -->

<!-- START RIGHT COL -->
<aside>
 <h3>Cited:</h3>
<P>
    <ul>
        <li>[1] https://thinkmobiles.com/blog/responsive-website-vs-mobile-app/
</li>
        <li>[2] https://belitsoft.com/apps-development-services/responsive-website-vs-mobile-app</li>
        <li>[3] https://www.smashstack.com/articles/the-pros-and-cons-of-mobile-apps-vs-responsive-web-design/</li>
    </ul>
</P>
</aside>
<!-- END RIGHT COL -->
 <?php include 'includes/footer.php';?>


